### ISSUE TITLE
Can't query with dblite

### ISSUE THREAD

**Issue by bass3l** [ghtorrent/ghtorrent.org#106]
Hello,
I'm trying a simple select query : 
``` SELECT * FROM users WHERE login = 'bass3l' ```

and I'm getting the following error message : 

 **SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'ghtro'@'web' for table 'users'**

I also tried registering so I can connect as a user and not as a guest ,but I get another error:

**Failed to open/create a writable database at [/home/gousiosg/dblite/data/database/users.sqlite]**

thx.

**Comment by gousiosg** [comment]
Due to privacy restrictions, you cannot `select * from users`.  You need to specify the specific fields you want to retrieve, other than `name` and `email`. See alos: http://ghtorrent.org/relational.html

Registration does not work.

**Comment by aarti9** [comment]
Hi Georgious,

How can I query MYSQL dblite for ghtorrent DB? I get the same error as reported in this post above. I also downloaded the latest dump file and extracted on my PC, but loading into MySQL workbench tables is taking forever.  

I do need the DB access for my research and would appreciate any help on accessing data.

Thanks
Aarti

**Comment by jovinod** [comment]
Hi @gousiosg , While trying to connect to the SQL lite DB I get the following error 

_**Failed to open/create a writable database at [/home/gousiosg/dblite/data/database/users.sqlite].**_ 

Is there a way I connect to this DB and use it for my research work?

Thanks Vinod
