### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by satazor** [ghtorrent/ghtorrent.org#121]
Hello!

I'm seeing outdated user data and also out of sync data between mongodb and mysql.

For instance, my user's location in mysql is `Porto, Portugal` (which is correct) but mongodb still says `Aveiro, Portugal`. I've changed my city to Porto years ago. Additionally, the company I work on is wrong in both dbs. Other fields such as the number of `followers` and `repositories` are also totally outdated.

What went wrong? Thanks in advance.

**Comment by gousiosg** [comment]
Please see: cfb121f
