### ISSUE TITLE
Lean ghtorrent broken or discontinued?

### ISSUE THREAD

**Issue by pascalu** [ghtorrent/ghtorrent.org#163]
I don't know if that's an issue or if the lean ghtorrent service has been discontinued and could also not find any information on this!

http://ghtorrent.org/lean.html returns an empty page where the submission form used to be. Inspection yielded that http://ghtorrent.org/lean/ endpoint seems to be gone.

**Comment by gousiosg** [comment]
It has been discontinued. You can find the source code that implemented it here: https://github.com/ghtorrent/ghtorrent-service
