### ISSUE TITLE
The biggest commit file decompression failed

### ISSUE THREAD

**Issue by buaaxzl** [ghtorrent/ghtorrent.org#178]
I downloaded the commit file from "http://dutihr.st.ewi.tudelft.nl/downloads/commits-1-dump.2015-08-04.tar.gz".   And then I decompressed it using the command "tar zxvf commits-1-dump.2015-08-04.tar.gz".
However, it failed and reported as follow : 

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

The file I downloaded is 974453319052 bytes, the same as the website holded. 

Is it possible that the compressed file is broken? Thank you!

**Comment by gousiosg** [comment]
You can find checksums here: http://dutihr.st.ewi.tudelft.nl/downloads/MD5SUM
```
tar tzvf commits-1-dump.2015-08-04.tar.gz 
```

completes without an issue for me
