### ISSUE TITLE
Bigquery dataset freshness

### ISSUE THREAD

**Issue by pascalu** [ghtorrent/ghtorrent.org#207]
The website is stating "Google BigQuery contains an up to date import of the latest GHTorrent MySQL dump"

The latest dump is dating 2017-02-01, the last modified timestamp of most tables in Bigquery is dating September 2016. Is this intended behavior or am I missing out on something?

**Comment by gousiosg** [comment]
Well, the latest dump is uploading to BigQuery; a few days of patience please :-)

**Comment by pascalu** [comment]
Thanks, I'll wait patiently ;)

**Comment by gousiosg** [comment]
You can try `ght_2017_01_19` now, or wait a bit more for `ght_2017_02_01`. Enjoy!

**Comment by fhoffa** [comment]
Wondering if this is the right place to request a new dump? Thanks!

**Comment by gousiosg** [comment]
So `ght_2018_04_01` has just finished uploading!
