### ISSUE TITLE
rows in multiple lines

### ISSUE THREAD

**Issue by zseder** [ghtorrent/ghtorrent.org#26]
I downloaded latest mysql dump (20150925) that contains csv files.
In textual fields, like in commit_comments.csv `body`, there are new line characters that are not escaped, so a data value can expand in multiple lines, and in this way, these files are hard to be handles as regular csv files.
Is this on purpose? If so, I can make a workaround script to handle these files, but maybe this is a bug in the exporter?

**Comment by gousiosg** [comment]
The exporter we use is MySQL's `SELECT INTO OUTFILE` to do the export. I 've only tested the import phase with 10 project GHTorrent instances. I 've started an import process of the full GHTorrent dump now, I will fix any issues found.

Thanks for reporting!

**Comment by gousiosg** [comment]
In the mean time, several users managed to import more recent MySQL dumps to their MySQL database instances (among other things) without an issue. Closing this, please re-open if you still think it is relevant.
