### ISSUE TITLE
issues schema

### ISSUE THREAD

**Issue by zseder** [ghtorrent/ghtorrent.org#27]
I am using the latest dump, 20150925.
In this file: http://ghtorrent.org/downloads/mysql-2015-09-25.tar.gz , there is `schema.sql` which lists the following schema for `issues` table:
~~~~
CREATE TABLE IF NOT EXISTS `ghtorrent`.`issues` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `repo_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `reporter_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `assignee_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `issue_id` MEDIUMTEXT NOT NULL COMMENT '',
  `pull_request` TINYINT(1) NOT NULL COMMENT '',
  `pull_request_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
...
~~~~

But the first 3 lines of the data looks like this:
~~~~
2,1334,345886,\N,0,\N,"2012-01-19 06:24:55",4535
3,1334,154788,\N,0,\N,"2012-01-26 16:07:56",4701
4,1334,26122,\N,0,\N,"2012-01-26 16:20:54",4702
~~~~

There is something wrong here, since in the data, date field is at last but one place (7th), but in the schema, `created_at` is the last (8th).

**Comment by gousiosg** [comment]
You are right. This is because different MySQL instances were used to create the dump and the schema file respectively.

It should be fixed in gousiosg/github-mirror@bfc304b0a0ade4 Could you check and comment?

**Comment by zseder** [comment]
Has the data dump file also changed or only the schema.sql?

**Comment by gousiosg** [comment]
Only the schema, I do not thing there is any problem with the data.

**Comment by zseder** [comment]
looks good now, so I'm closing the issue, thank you!
