### ISSUE TITLE
wrong "updated_at" in the table "projects"

### ISSUE THREAD

**Issue by tao-ji** [ghtorrent/ghtorrent.org#291]
When I execute the sql "select * from projects where name="Glomes";​​​​​​", mysql returns three results just as shown in the figure.
![image](https://user-images.githubusercontent.com/19903046/29543917-2e0c3d2e-8717-11e7-88fd-c4b68ef945ee.png)
Obviously, the third result's "updated_at" is wrong. And I check the first result's "updated_at", it should be "2014-03-16T02:53:25Z" according to the github API.

**Comment by gousiosg** [comment]
`updated_at` tracks the time GHTorrent last run a full update cycle. It does not correspond to GitHub's `updated_at`.
