### ISSUE TITLE
research data is not anonymized

### ISSUE THREAD

**Issue by cainlevy** [ghtorrent/ghtorrent.org#35]
I would request that best effort be made to anonymize this data set before redistribution. This is best practice with academic research.
## but it's already public

GHTorrent takes technically available information and lowers the bar to access, thereby making it available to a greater number of people with less effort and resources.
## but others are doing it

I would like them to do the same.
## but GitHub allows it

Maybe not. And even if they do, ethical conventions and best practices with research data are to make a good faith, best effort attempt at anonymizing.
## but it diminishes the usefulness of the data

Yes, it does. Anonymizing data constrains both legitimate and illegitimate uses of the data. It's a reasonable and common trade off because it limits abuse more than it limits utility.

**Comment by gousiosg** [comment]
Best summary ever. Thanks! Let's be constructive this time.

Which parts would you like to see anonymized?

**Comment by cainlevy** [comment]
I think [personally identifying information](https://en.wikipedia.org/wiki/Personally_identifiable_information) exists on a spectrum, but much of the information in the `users` table could be construed as personal. A few parts stand out in particular:

## user attributes

### user name

What are some use cases for this in academic research? Guessing gender or ethnicity? That would be fairly sensitive research, and while I'm sure there's an interesting paper to be found in that data it's something I'd rather was only available to determined individuals.

### email

This provides an easy join key from the GHTorrent data set to many other data sets. A hash of the email would fix that, but end up creating a redundant internal unique key that is redundant with the table's primary key.

Maybe another way to handle this field would be extracting and storing only the domain name. That might allow insight into `.edu` vs `.gov` behavior, for example, while providing relative anonymity to people that have not registered personal email domains.

### location

Would it make sense for this data set to only keep country, or possibly state? I would imagine that there's less academic value in providing city.

### login name

This makes it easy for a person to join GHTorrent data against GitHub and rediscover any of the anonymized data. What's the minimum information that the data harvester needs to connect commits by a person together? If login name is not needed, I'd be in favor of dropping it entirely. It's difficult to imagine interesting academic analysis on this field.

## users in general?

Could this data set continue to provide a large amount of the value you seek without the concept of a user? For example, maybe commits could denormalize the most useful user attributes like country and email domain without relying on any unique user identifier?

I realize this probably means that the data harvester would need an internal, private data set of users so that it didn't require inefficient API and geocoding calls for every new commit. The difference, I think, would be entirely in how the data is publicized.

**Comment by gousiosg** [comment]
Thanks a lot! Here are some comments:

* **User name**: Yes, identifying gender and ethnicity are the two primary reasons on why I think this is important. Perhaps an option might be that GHTorrent resolves gender and ethnicity internally and then removes the user name. The research you mention has [been](https://peerj.com/preprints/1733/) [partially](http://gousios.gr/bibliography/RNG16.html) [done](http://dl.acm.org/citation.cfm?id=2702549).

* **Email**: This was the main reason for #32. Frankly, I do not see any solution other than hashing it out. I explained the reasons why I think it is pointless from a privacy POV. @lazerwalker [explained very well](https://github.com/ghtorrent/ghtorrent.org/issues/32#issuecomment-189400935) why hashing is a must do. The `email` field is already a primary key, as is the `login` field.

* **Location**: This was actually added very recently. This gives the opportunity to study things such as developer hotspots and even migration behaviour. I do not have an opinion on how sensitive this information is; I understand that is a different thing to say "location: NY" and "location: Delft".

* **login and the users table**: What makes GHTorrent so great for us researchers is that a single login (== entry in users table) links together all activity a user has taken part on GitHub. Omitting the users table will basically destroy any querying value GHTorrent has. The `login` field can be omitted from the final dump at the expense of being way more difficult to check the validity of certain analyses against GitHub itself (e.g. did a predicted user X indeed close a PR?).

The above is the "theory" side. On the technical side, GHTorrent can still collect internally the same information but only distribute restricted MySQL data dumps (and restrict access to specific columns in the online version) for the users table. This way, no technical modifications (apart perhaps from hashing emails) are required and people can still download the GHTorrent [data harvester](https://github.com/gousiosg/github-mirror) and use it locally. The MongoDB data dumps are unprocessed, unlinked replies from the GitHub API so I do not think they need to be anonymized (I am open to suggestions).

**Comment by cainlevy** [comment]
Thanks for discussing this!

**User name:** I don't consider myself in a good position to guess how folks would react to inferred gender and ethnicity attributes being redistributed in a public data set. But I do think it could go over poorly, even if it meant that the user's name was less available. Seeing an academic paper that has used names to infer demographic information in aggregate is probably less alarming to folks than seeing a public data set making it easily accessible on an individual level.

**Email:** It sounds like everyone is in agreement on email. I'm not sure how much value a hashed email would have in a public data set, but it's not PII at that point so I'd defer entirely to you.

**Location:** Perhaps start by only providing coarse data? That would permit some interesting geographic analysis without redistributing developer hometowns (even if they've chosen to add it to their GitHub profile). I can't anticipate how sensitive precise location data would be either, but I'd err on the side of minimizing PII.

**Login:** The best argument I've come up with for obscuring login names is actually an account security concern. If a blackhat could left join a [large database breach](https://haveibeenpwned.com/) against the GHTorrent data set on either login name or email address, it would make them more efficient at probing for password reuse by allowing them to skip accounts with no match.

**Restricted MySQL dumps:** This seems like a promising direction. I think folks trust academic researchers to treat data responsibly, but worry about the data leaking into the wrong hands. Anything you can do to minimize exposure of mass amounts of PII would be helpful.

If the MongoDB data dumps are secured and only accessible to a few people that you trust, I do not believe they would need to be anonymized. One way to minimize exposure of these data dumps would be to decouple read and write permissions and be more permissive with write permissions. I'm not familiar with your project's ingestion process so I can't say if this even makes sense for you; it's just an idea!

**Comment by Plazmaz** [comment]
Hi, I'm hoping to use ghtorrent to provide a public service that would require email access to inform people of accidentally uploaded data leaks. This would completely destroy my ability to use your tool for this project. Git allows for the changing of email, first/last name, and other things. It is essential to my project that this is not implemented. Though I can understand the reasoning, lowering the bar to access **does not** change the fact that this data is already public. I opened an issue to GitHub a while ago about this issue, and they did not seem at all concerned. Please keep in mind that your service can be and likely is used for more than purely research related purposes.

**Comment by gousiosg** [comment]
I am sorry about this; the EU has laws regarding usage of personal information which GHTorrent cannot ignore. You can definitely go from logins (included in the data dumps) to emails very easily, but this is a step you will have to take (along with any possible consequences).

See here for more: https://speakerdeck.com/gousiosg/the-number-issue32-incident
