### ISSUE TITLE
what is the password for online services

### ISSUE THREAD

**Issue by daksunt** [ghtorrent/ghtorrent.org#36]
Online mongodb requires password. 

ssh -L 27017:dutihr.st.ewi.tudelft.nl:27017 ghtorrent@dutihr.st.ewi.tudelft.nl

ghtorrent@dutihr.st.ewi.tudelft.nl's password: ???

**Comment by slang800** [comment]
http://ghtorrent.org/services.html says:

> To obtain access to any of the [services], send us [your] public SSH key
