### ISSUE TITLE
When will the public mongodb copy be available again?

### ISSUE THREAD

**Issue by maxthemillion** [ghtorrent/ghtorrent.org#381]
As you noted on twitter, the github db is currently not available. Unfortunately, I currently work on a thesis which relies heavily on your mongodb database. So it would be very helpful for me to know approximately, when the publicly accessible mongodb copy will be available again. Could you give a rough estimation? In case it took longer, I would have to look for alternatives and some info on that would really help me out. Thank you very much!

**Comment by gousiosg** [comment]
It is currently available.
