### ISSUE TITLE
Incorrect user type

### ISSUE THREAD

**Issue by dspinellis** [ghtorrent/ghtorrent.org#410]
At least one user is incorrectly identified as `USR` rather than `ORG` in the `mysql-2018-01-01` dataset.

```
MariaDB [ghtorrent]> select login, type from users where id=234594;
+--------+------+
| login  | type |
+--------+------+
| docker | USR  |
+--------+------+
```

The GitHub API correctly [returns](https://api.github.com/users/docker) `type | "Organization"`.

**Comment by dspinellis** [comment]
Here are some more users for which GitHub returns "Organization" that are marked as `USR` on GHTorrent.

android apple axios bokeh bower callemall Carthage casperjs cefsharp
chartjs chef Cocoanetics cocos2d codeschool-projects curl d3 dcloudio
DefinitelyTyped designmodo desktop dianping didi discourse docker dokku
ecomfe edx elastic electron esp8266 explosion expressjs FallibleInc
fastai firebase freeCodeCamp FreeCodeCamp gollum grab greatfire happyworm
infinitered influxdata Intervention iview jasmine jekyll leanote lerna
less lewagon minio moby moment mysqljs nodejs npm nsqio nuxt opencart
opencv openframeworks openssl pallets phalcon pivotal plotly PokemonGoF
poole PowerShell prettier prometheus Qihoo360 Quick rancher raspberrypi
rbenv realm relax requirejs revel riot roots rtfd ServiceNow servo
springside svg telegramdesktop Tencent thinkgem thx tmux uxsolutions v2ray
v8 vapor venomous0x videolan vim visionmedia weui Yalantis zeit zxing

**Comment by gousiosg** [comment]
This is because initially those accounts where user accounts before they where converted to organisations. The solution to that would be to re-fetch all user data from GitHub and update the MySQL database as necessary.

**Comment by dspinellis** [comment]
That make s sense. I think that the current `type` field of users is so inaccurate as to be useless. Updating would be useful. I can easily create an update script, but with GitHub's API access limits, it would take me 20 years to get updates on 22 million users.

Here is another batch of popular users for which GitHub returns "Organization" that are marked as `USR` on GHTorrent.

alcatraz allmobilize alvarcarto Apple baidu BoLT Bower careercup carthage
chalk Coding DaoCloud densitydesign este evolus Firebase freebsd haltu
hashcat iovisor iron Itseez jasperproject llvm-mirror Maatwebsite mailgun
mdn MinecraftForge minetest Minio noraesae OpenCV openhab Oracle Ory
Poole powershell PowerShellMafia PuerkitoBio qmk quick Rancher Realm
REVEL scalaz servicenow stylus SVG tencent tools trello webpy yandex
YouTube Zeit

**Comment by gousiosg** [comment]
GHTorrent does have a process to do those updates this in parallel, but it did not include updating the `type` field. This is now fixed: https://github.com/gousiosg/github-mirror/commit/d95b3cacc227daf8f9736ff2351da8dbed66fd03

Now, I need to re-run the refresh process, but as you might expect it will take a while...

**Comment by dspinellis** [comment]
:+1:

**Comment by gousiosg** [comment]
This was finished almost a month ago. All the examples you referenced above are now listed as `ORG`s

**Comment by gousiosg** [comment]
BTW, the change should be reflected in dump `mysql-2018-06-01.tar.gz`
