### ISSUE TITLE
Public key in keys file but access denied

### ISSUE THREAD

**Issue by FAUSheppy** [ghtorrent/ghtorrent.org#434]
ssh-keygen -y -f ~/.ssh/gitrsa && wget -O- -q "https://raw.githubusercontent.com/ghtorrent/ghtorrent.org/master/keys.txt" | grep sheppy
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+tKGbk8UL+JPlwMskNpf/sG6X1X4uCcHE7VgK+f6JtfQNBu7/Ky4jSLKuUwiBTmnyCBGUnstFpJrioFNE9W7bTpKAxMnMdEfbW8hnmh/YJmMZTt22P1LKHHMdwy+G5Fp/BenpgLNzOnx6Lc2oDADRDvNeIVMbH9iWZSxH0T2ZW+JNQX7FhnmlR97jUaq78LlW6DLg0HHkwszAdSk8RsoTBuTttEykokdj6y5M9fBzXjyGKImXuAqEeV/piXMejicxrcMiSYLT8RFYn6YufdKOkBqEa2ML9/8VY1gYwKAjzNZsjGBD67vb5/I+hYiTXCkT3Xi8B4JyWrf5oiQEf1PC83RXPc2sit+i9k7PysQZYCvMQHnnYJbbfKxfgz2Od9N3F3jlOP2v3PK2nQx1AKN7ji69I4Z7tdvwM2HZRmq1V5gahNIeRkNq7QLHFvdLMTdwTp9uR9+pHDrkHmzN84O7RneF7NdARNNrIASgHF8vy993mGwDcfmEJYcDVWQ3Z35Mwxz8EWGcfflZA7RUX/sKbSYlvqEN94PBjixVxYUNLbAk+aFg23TaPPnav67gP24lMHA6yUoRwwdOR3S5pniZnhyAKBA3M9K5/Jl8dC2FeESdlG1utn0p65DQEqUdA8jbfki/j91S2bqX7ZJOD5DQH9gu6x19c9O0B7dXR2orRQ==
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+tKGbk8UL+JPlwMskNpf/sG6X1X4uCcHE7VgK+f6JtfQNBu7/Ky4jSLKuUwiBTmnyCBGUnstFpJrioFNE9W7bTpKAxMnMdEfbW8hnmh/YJmMZTt22P1LKHHMdwy+G5Fp/BenpgLNzOnx6Lc2oDADRDvNeIVMbH9iWZSxH0T2ZW+JNQX7FhnmlR97jUaq78LlW6DLg0HHkwszAdSk8RsoTBuTttEykokdj6y5M9fBzXjyGKImXuAqEeV/piXMejicxrcMiSYLT8RFYn6YufdKOkBqEa2ML9/8VY1gYwKAjzNZsjGBD67vb5/I+hYiTXCkT3Xi8B4JyWrf5oiQEf1PC83RXPc2sit+i9k7PysQZYCvMQHnnYJbbfKxfgz2Od9N3F3jlOP2v3PK2nQx1AKN7ji69I4Z7tdvwM2HZRmq1V5gahNIeRkNq7QLHFvdLMTdwTp9uR9+pHDrkHmzN84O7RneF7NdARNNrIASgHF8vy993mGwDcfmEJYcDVWQ3Z35Mwxz8EWGcfflZA7RUX/sKbSYlvqEN94PBjixVxYUNLbAk+aFg23TaPPnav67gP24lMHA6yUoRwwdOR3S5pniZnhyAKBA3M9K5/Jl8dC2FeESdlG1utn0p65DQEqUdA8jbfki/j91S2bqX7ZJOD5DQH9gu6x19c9O0B7dXR2orRQ== sheppyspammail@web.de

but:
ssh -o "PreferredAuthentications=publickey" -i ~/.ssh/gitrsa -L 27017:dutihr.st.ewi.tudelft.nl:27017 ghtorrent@dutihr.st.ewi.tudelft.nl
Permission denied (publickey,password).

**Comment by gousiosg** [comment]
It should work now; please check and let me know.

**Comment by FAUSheppy** [comment]
works thx man!
