### ISSUE TITLE
Project/user id does not match the id from GitHub API

### ISSUE THREAD

**Issue by yklin82** [ghtorrent/ghtorrent.org#448]
I have downloaded and loaded the 2018-04-01 mysql dump. I notice that the id values in ghtorrent's projects and users tables do not match the id values from the GitHub API. 

For example, in the users table, docker has the id 234594, but the GItHub API (https://api.github.com/users/docker) shows that docker has the id 5429470. I have tried many user/project ids, and all have the same issue.

**Comment by gousiosg** [comment]
The `id` field is internal to GHTorrent, not a mirror of what GitHub reports as `id`.
