### ISSUE TITLE
Can not connect to the mongodb server

### ISSUE THREAD

**Issue by arefindk** [ghtorrent/ghtorrent.org#46]
When I try to connect to the server using following command:

`ssh -L 27017:dutihr.st.ewi.tudelft.nl:27017 ghtorrent@dutihr.st.ewi.tudelft.nl` it says that `PTY allocation request failed on channel 2`. 

Then on a new tab I use the following command:
`mongo -u ghtorrentro -p ghtorrentro github`

Then it does not connect to the mongodb shell. It produces the following error message:
```
MongoDB shell version: 3.2.4
connecting to: github
2016-05-26T22:47:22.137-0400 E QUERY    [thread1] Error: network error while attempting 
to run command 'isMaster' on host '127.0.0.1:27017'  :
connect@src/mongo/shell/mongo.js:224:14
@(connect):1:6

exception: connect failed
```

Also in the previous tab a new message appears which is:
`channel 3: open failed: administratively prohibited: open failed`

Can you suggest me how can I connect to the mongo shell on your server?

**Comment by gousiosg** [comment]
Thanks for reporting this! There was an error on the server SSH forwarding configuration. It should be working now, please re-open if it does not.
