### ISSUE TITLE
Double Entries is MongoDB

### ISSUE THREAD

**Issue by FAUSheppy** [ghtorrent/ghtorrent.org#463]
Iterating over 'repos' in the MongoDB gives me a vast number of duplicate, triplicate (or more in some cases) entries.

Example of a duplicate I got:
full_name: rschanafelt/gregf-dotfiles
id: 79398522

I can provide a full list of duplicates if necessary.

**Comment by FAUSheppy** [comment]
Possilby related https://github.com/ghtorrent/ghtorrent.org/issues/76 ?

**Comment by gousiosg** [comment]
This is to be expected due to the way the backups are done. The MongoDB backups are additive. The MongoDB instance you are querying is effectively much larger than the real database, as it was restored from backups. You should always use the latest version of any repository.
