### ISSUE TITLE
May 2018 Dump is Incomplete

### ISSUE THREAD

**Issue by CaptainEmerson** [ghtorrent/ghtorrent.org#471]
Regarding this dump:
http://ghtorrent-downloads.ewi.tudelft.nl/mysql/mysql-2018-05-01.tar.gz

The file is about half the size of prior months, and only contains 5 tables. I'd expect it to be the same size and have at least as many tables as prior months.

**Comment by gousiosg** [comment]
Indeed. There is a new dump available [mysql-2018-06-01](http://ghtorrent-downloads.ewi.tudelft.nl/mysql/mysql-2018-06-01.tar.gz), you could perhaps use that one.
