### ISSUE TITLE
Can not connect to the mongodb server

### ISSUE THREAD

**Issue by joaohelis** [ghtorrent/ghtorrent.org#50]
When I try to connect to the server using following command:

 ssh -L 27017:dutihr.st.ewi.tudelft.nl:27017 ghtorrent@dutihr.st.ewi.tudelft.nl 

it says that:

bind: Address already in use
PTY allocation request failed on channel 1

Then on a new tab I use the following command:
mongo -u ghtorrentro -p ghtorrentro github

Then it does not connect to the mongodb shell. It produces the following error message:

MongoDB shell version: 3.0.6
connecting to: github
2016-06-02T18:16:20.142-0300 E QUERY    Error: 18 Authentication failed.
    at DB._authOrThrow (src/mongo/shell/db.js:1271:32)
    at (auth):6:8
    at (auth):7:2 at src/mongo/shell/db.js:1271
exception: login failed

Can you suggest me how can I connect to the mongo shell on your server?

**Comment by gousiosg** [comment]
```bind: Address already in use``` → This means that you are trying to connect to your local MongoDB instance. The GHTorrent infrastructure works as it should.
