### ISSUE TITLE
The two big commits file downloads URLs are down

### ISSUE THREAD

**Issue by gpitfield** [ghtorrent/ghtorrent.org#58]
Hi, I'm trying to download http://dutiht.st.ewi.tudelft.nl/downloads/commits-dump.2015-08-03.tar.gz and http://dutiht.st.ewi.tudelft.nl/downloads/commits-1-dump.2015-08-04.tar.gz from the downloads page, but neither link seems to resolve. Is this something you can fix, and/or is there another place to download those files? Thanks!

**Comment by gousiosg** [comment]
The machine that hosted those was offline for some time. I am copying the data to a more persistent location and will then link them there. Keeping the issue open till then.

**Comment by gpitfield** [comment]
Thanks for the update Georgios. Not sure if you meant to, but it looks like you closed the issue. I don't mind either way; just an fyi in case it helps with housekeeping :-)

**Comment by gousiosg** [comment]
Hi, the downloads have now been restored. Thanks for reporting!
