### ISSUE TITLE
Cannot connect to GHTorrent

### ISSUE THREAD

**Issue by mahills** [ghtorrent/ghtorrent.org#59]
I'm currently trying to connect to GHTorrent and am not having any luck with either MySQL or MongoDB. Using ssh with debug on, this is the last message I see:

    debug1: Connecting to web.ghtorrent.org [104.208.163.52] port 3306.
    debug1: connect to address 104.208.163.52 port 3306: Operation timed out
    ssh: connect to host web.ghtorrent.org port 3306: Operation timed out

or

    debug1: Connecting to dutihr.st.ewi.tudelft.nl [131.180.26.164] port 27017.
    debug1: connect to address 131.180.26.164 port 27017: Operation timed out
    ssh: connect to host dutihr.st.ewi.tudelft.nl port 27017: Operation timed out

Port 22 is responsive on `web.ghtorrent.org` (I didn't try to log in, but I get that far), so the machine itself appears to be available. I've tried from both my university network and my home network and it fails on both, so it doesn't appear to be an issue with the university firewall.

**Comment by gousiosg** [comment]
I can connect to MySQL (even though VERY slowly and get some timeouts as well); Azure's networking is probably to blame for this.

The MongoDB machine is currently offline due to networking re-organization at TU Delft.
