### ISSUE TITLE
Misaligned users table in the 2016-06-16 data set

### ISSUE THREAD

**Issue by dspinellis** [ghtorrent/ghtorrent.org#70]
The fields `location`, `created_at`, `country_code`, and `city` seem to be incorrect.

```
mysql> select * from users where login='dspinellis'\G
*************************** 1. row ***************************
          id: 8577
       login: dspinellis
     company: Athens University of Economics and Business
    location: 2011-11-22 10:25:12
  created_at: 0000-00-00 00:00:00
        type: 0
        fake: 0
     deleted: 38
        long: 0.00000000
         lat: 0.00000000
country_code: Αθή
       state: Athens, Greece
        city: NULL
1 row in set (0.00 sec)
```

**Comment by dspinellis** [comment]
Seems related to #60.

**Comment by dspinellis** [comment]
The problem is that the `schema.sql` distributed with the data set differs from the one in the repo. The one in the repo is correct.

## Distributed
```
CREATE TABLE IF NOT EXISTS `ghtorrent`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(255) NOT NULL COMMENT '',
  `company` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `location` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `type` VARCHAR(255) NOT NULL DEFAULT 'USR' COMMENT '',
  `fake` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `long` DECIMAL(11,8) COMMENT '',
  `lat` DECIMAL(10,8) COMMENT '',
  `country_code` CHAR(3) COMMENT '',
  `state` VARCHAR(255) COMMENT '',
  `city` VARCHAR(255) COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
```

## Repo
```
CREATE TABLE IF NOT EXISTS `ghtorrent`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(255) NOT NULL COMMENT '',
  `company` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `type` VARCHAR(255) NOT NULL DEFAULT 'USR' COMMENT '',
  `fake` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `long` DECIMAL(11,8) COMMENT '',
  `lat` DECIMAL(10,8) COMMENT '',
  `country_code` CHAR(3) COMMENT '',
  `state` VARCHAR(255) COMMENT '',
  `city` VARCHAR(255) COMMENT '',
  `location` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
```

**Comment by gousiosg** [comment]
Yes, I fixed this issue (hopefully) a couple of days ago. Unfortunately, it is not possible to recreate the dumps. If the version of `schema.sql` in the repo works for you, please close this issue.

**Comment by gousiosg** [comment]
An idea could be to get the latest version of the schema directly from the repo instead of including it in the dump tar. What do you think?

**Comment by dspinellis** [comment]
That's the temporary workaround I will adopt. However the schema must be included in the dump because it  can change. Alternatively the dump must include the SHA of the software used. 

<div>-------- Original message --------</div><div>From: Georgios Gousios <notifications@github.com> </div><div>Date:03/07/2016  11:05  (GMT+02:00) </div><div>To: "ghtorrent/ghtorrent.org" <ghtorrent.org@noreply.github.com> </div><div>Cc: Diomidis Spinellis <dds@aueb.gr>, Author <author@noreply.github.com> </div><div>Subject: Re: [ghtorrent/ghtorrent.org] Misaligned users table in the
  2016-06-16 data set (#70) </div><div>
</div>An idea could be to get the latest version of the schema directly from the repo instead of including it in the dump tar. What do you think?

**Comment by gousiosg** [comment]
Indeed. Thanks for the feedback!
