### ISSUE TITLE
Unable to Access the MySQL database

### ISSUE THREAD

**Issue by MattCrepea** [ghtorrent/ghtorrent.org#81]
Hello, I don't know if anyone else has this issue or if it's just me. A few weeks ago I was able to successfully connect to the MySQL database and query the 'ghtorrent' database successfully with a Cygwin terminal. When I attempted to query the server today, I was able to successfully ssh into the MySQL machine and connect to the MySQL server; unfortunately, the database 'ghtorrent' was unavailable. When I attempted to run the command
`mysql -u ght -h 127.0.0.1 ghtorrent`
I received the error message
`ERROR 1044 (42000): Access denied for user ''@'localhost' to database 'ghtorrent'`.
As far as I can tell, the 'ghtorrent' database is simply not there.

Also, I don't know if this is related or can help at all, but the MySQL web service at [http://ghtorrent.org/dblite/](url) reports the error message `SQLSTATE[42000] [1044] Access denied for user 'ghtro'@'%' to database 'ghtorr`.

Any advice would be appreciated. Thank you.

**Comment by gousiosg** [comment]
It should be fixed now.
