### ISSUE TITLE
Missing pull requests comments in file pull_request_comments.csv

### ISSUE THREAD

**Issue by mariamelm2** [ghtorrent/ghtorrent.org#82]
Hello,

First, I would like to thank you for providing this valuable dataset.
I am working with the GHTorrent files provided in csv format, to extract information related to pull requests (using the dump released on 2016-02-01).
During this process, I noticed that some pull requests which are present in the file _pull_requests.csv_ are missing in the _pull_request_comments.csv_, even if some of them do have comments when I checked on their associated pages on GitHub.

Here are few examples:

-  Pull Request ID:  4194634,  GitHub URL: https://github.com/opensim-org/opensim-core/pull/78
-  Pull Request ID:  1042149,  GitHub URL: https://github.com/ivansafrin/Polycode/pull/37
-  Pull Request ID:  2101900,  GitHub URL: https://github.com/sympy/sympy/pull/2454
-  Pull Request ID:  9431083,  GitHub URL: https://github.com/qreal/qreal/pull/1606

The pull request ID shown here refers to the field called _id_ in the file _pull_requests.csv_.
I have a long list of missing pull requests from the  the  _pull_request_comments.csv_ file (~2M). I could not check if all of them have associated GitHub pages, but out of the ones I checked, all pull requests do have discussion pages with some content.

Is this missing data or am I missing something?

Thanks for your time!

**Comment by gousiosg** [comment]
As per the documentation [here](http://ghtorrent.org/relational.html#pull_request_comments) `pull_request_comments` contains code review comments for code reviews happening in pull requests. For PR discussion comments, you should be looking in the contents of `issue_comments`.

**Comment by mariamelm2** [comment]
Thanks a lot for the clarification and the prompt reply!

**Comment by alirezaeinassab** [comment]
The `issue_comments` table just shows the number of comments in issues and PRs but how to access context of these comments?
