### ISSUE TITLE
No new daily mongo db dumps since 2016-07-19

### ISSUE THREAD

**Issue by kelewis** [ghtorrent/ghtorrent.org#85]
http://ghtorrent.org/downloads.html doesn't have any new daily files listed since 2016-07-19.

**Comment by kelewis** [comment]
Is there anything we can do about the missing dumps?  It has delivered dumps up to 2016-08-08 with a few gaps in between.  We're over 20 days behind now.

Let me know if I can lend a hand in any way.

**Comment by gousiosg** [comment]
Hi, apologies, I was extremely busy lately; new dumps are being uploaded, when all the dumps till the end of August are done, I will switch the daily dump generator back again.
