### ISSUE TITLE
Invalid Datetimes

### ISSUE THREAD

**Issue by dzoba** [ghtorrent/ghtorrent.org#86]
When restoring the projects table using ```./ght-restore-mysql``` I get the following error:

```
Thu Jul 28 02:59:59 PDT 2016 Restoring table projects
ERROR 1292 (22007) at line 1: Incorrect datetime value: '0000-00-00 00:00:00' for column 'updated_at' at row 1
```

In the CSV, I do see ```0000-00-00 00:00:00``` in some entries.  As a work around, I change the entries to valid times with this command: 

```
sed -i -e 's/0000-00-00 00:00:00/2000-01-01 11:17:27/g' projects.csv
```

The import seems to get past this problem step at this point, however its not ideal since this isn't the actual date time, and running this command on the csv takes quite a while.

I am using OSX and ```mysql  Ver 14.14 Distrib 5.7.12, for osx10.11 (x86_64) using  EditLine wrapper```

**Comment by gousiosg** [comment]
It looks like that MySQL > 5.7.4 cannot use `0000-00-00 00:00:00` as default value for timestamp fields in [strict mode](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes) (the default). This is not a problem with MariaDB that GHTorrent is using on the server side (just finished restoring the latest dump).
